language: go

go:
  - 1.12.1

before_install:
- export GO111MODULE='on'
- go get -u github.com/mgechev/revive
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega/...
- export PATH=$PATH:$GOPATH/bin
- export CGO_LDFLAGS_ALLOW='-msse2,-mavx'
- export CGO_CFLAGS_ALLOW='-msse2,-mavx'
- go get ./...

script:
- travis_wait 30 ginkgo -tags="pow_avx pow_sse pow_c pow_c128" -r --skipPackage=mongo --randomizeSuites --failOnPending --cover --progress

after_success:
- revive -config revive.toml -formatter stylish -exclude ./api/integration/... ./...